# Generated by Django 4.1.4 on 2023-01-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_category_note_remove_orderdetail_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
